apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myd
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: ayush122001/test
        name: test
