apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 1
  selector:
    matchLabels:
app: myd
  template:
    metadata:
creationTimestamp: null
labels:
app: myd
    spec:
containers:
- image: ayush122001/test
name: test
~                   
